### ISSUE TITLE
PROBLEMS WITH WEBHOOK

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce-rest-api-docs#192]
WHEN I RUN THE CODE BELOW, I RETURN THE FOLLOWING ERROR:

 _{"code": "rest_no_route", "message": "No route was found that matches the URL and the request method.", "Date ": {" status ": 404}}_

```
WooCommerce.get("webhooks/142/deliveries/")
  .then((response) => {
    console.log(response.data);
  })
  .catch((error) => {
    console.log(error.response.data);
  });
```

**Comment by claudiosanches** [comment]
Hello @creuza,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

Also note that `deliveries` is obsolete and we removed those from our documentation.

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
